{% set name = "catsmoothing" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/catsmoothing-{{ version }}.tar.gz
  sha256: 647de72560733df9b3fb5dd9870cbb2584dbeda47a08430f767fdbee22f0725c

build:
  skip: true  # [py<=39]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - libclang
    - clang
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - setuptools
    - wheel >=0.29.0
    - pip
  run:
    - python
    - numpy >=2
    - shapely >=2

test:
  imports:
    - catsmoothing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/catsmoothing
  summary: Smoothing Shapely geometries using CatMull-Rom spline
  doc_url: https://catsmoothing.readthedocs.io
  dev_url: https://github.com/cheginit/catsmoothing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
