schema_version: 1

context:
  version: 0.4.1

package:
  name: catsmoothing
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/catsmoothing/catsmoothing-${{ version }}.tar.gz
  sha256: 826342ce96bc8700baa267290bdd56d4fad52079f348142a71927021c20139a7

build:
  number: 0
  skip:
    - if: match(python, "<3.10")
      then: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.4,<2.0
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - libclang
    - clang
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python
    - numpy >=2
    - shapely >=2

tests:
  - python:
      imports:
        - catsmoothing
      pip_check: true

about:
  summary: Smoothing Shapely geometries using Catmull-Rom spline
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/cheginit/catsmoothing

extra:
  recipe-maintainers:
    - cheginit
